import { describe, expect, it } from "vitest";
import { compileTheme } from "@s9rg/theme-compiler";
import type {
  ResolvedColor,
  ThemeGraph,
  ThemeProject,
} from "@s9rg/theme-compiler";
import { createTailwindAdapter, tailwindAdapterManifest } from "./index.js";

const brand: ResolvedColor = {
  colorSpace: "srgb",
  components: [0, 0.4, 0.8],
  alpha: 1,
  hex: "#0066cc",
};
const white: ResolvedColor = {
  colorSpace: "srgb",
  components: [1, 1, 1],
  alpha: 1,
  hex: "#ffffff",
};
const navy: ResolvedColor = {
  colorSpace: "srgb",
  components: [0.02, 0.04, 0.08],
  alpha: 1,
  hex: "#050a14",
};

function graph(): ThemeGraph {
  return {
    schemaVersion: "1.0",
    projectId: "acme",
    projectName: "Acme",
    primitives: [
      { id: "white", $type: "color", value: white },
      { id: "brand", $type: "color", value: brand },
      { id: "navy", $type: "color", value: navy },
    ],
    schemes: [
      {
        id: "light",
        roles: {
          "primary-foreground": {
            role: "primary-foreground",
            ref: "white",
            value: white,
          },
          primary: { role: "primary", ref: "brand", value: brand },
          background: { role: "background", ref: "white", value: white },
        },
      },
      {
        id: "dark",
        roles: {
          background: { role: "background", ref: "navy", value: navy },
          primary: { role: "primary", ref: "brand", value: brand },
          "primary-foreground": {
            role: "primary-foreground",
            ref: "white",
            value: white,
          },
        },
      },
    ],
  };
}

describe("Tailwind adapter", () => {
  it("exposes its Tailwind v4 capability manifest", () => {
    expect(tailwindAdapterManifest).toMatchObject({
      id: "tailwind@4",
      engineApiVersion: "1",
      maturity: "beta",
      target: { name: "tailwindcss", version: ">=4 <5" },
      capabilities: {
        colors: { native: "passthrough", fallback: "none" },
        schemes: { count: "multiple", ids: "any" },
        preview: true,
      },
      options: { prefix: { type: "string", default: "theme" } },
    });
  });

  it("snapshots normalized options at factory creation", async () => {
    const options = { prefix: "Product Brand", darkSelector: ".night" };
    const adapter = createTailwindAdapter(options);
    options.prefix = "changed";
    options.darkSelector = ".changed";

    expect(adapter.configuration).toEqual({
      prefix: "product-brand",
      darkSelector: ".night",
    });
    const result = await adapter.compile(graph(), {});
    expect(result.artifacts[0]?.content).toContain(
      "--product-brand-semantic-primary:",
    );
    expect(result.artifacts[0]?.content).toContain(".night {");
  });

  it("emits top-level primitive @theme variables and inline semantic aliases", async () => {
    const adapter = createTailwindAdapter();
    const first = await adapter.compile(graph(), {});
    const source = graph();
    const reordered: ThemeGraph = {
      ...source,
      primitives: [...source.primitives].reverse(),
      schemes: [...source.schemes].reverse().map((scheme) => ({
        ...scheme,
        roles: Object.fromEntries(Object.entries(scheme.roles).reverse()),
      })),
    };
    const second = await adapter.compile(reordered, {});
    const content = first.artifacts[0]?.content;

    expect(first.artifacts).toEqual(second.artifacts);
    expect(content)
      .toBe(`/* Generated by @s9rg/theme-adapter-tailwind for Tailwind CSS v4. */

@theme {
  --color-palette-brand: color(srgb 0 0.4 0.8);
  --color-palette-navy: color(srgb 0.02 0.04 0.08);
  --color-palette-white: color(srgb 1 1 1);
}

:root {
  --theme-semantic-background: color(srgb 1 1 1);
  --theme-semantic-primary: color(srgb 0 0.4 0.8);
  --theme-semantic-primary-foreground: color(srgb 1 1 1);
}

[data-theme="dark"] {
  --theme-semantic-background: color(srgb 0.02 0.04 0.08);
  --theme-semantic-primary: color(srgb 0 0.4 0.8);
  --theme-semantic-primary-foreground: color(srgb 1 1 1);
}

@theme inline {
  --color-background: var(--theme-semantic-background);
  --color-primary: var(--theme-semantic-primary);
  --color-primary-foreground: var(--theme-semantic-primary-foreground);
}
`);
    expect(first.preview).toMatchObject({
      kind: "tailwind-theme",
      aliases: { "--color-primary": "var(--theme-semantic-primary)" },
    });
  });

  it("preserves wide-gamut CSS syntax and scheme alpha", async () => {
    const vivid: ResolvedColor = {
      colorSpace: "oklch",
      components: [0.72, 0.28, 12],
      alpha: 0.75,
      hex: "#ff3366",
    };
    const source = graph();
    const wideGamut: ThemeGraph = {
      ...source,
      primitives: [{ id: "vivid", $type: "color", value: vivid }],
      schemes: [
        {
          id: "light",
          roles: { primary: { role: "primary", ref: "vivid", value: vivid } },
        },
      ],
    };
    const result = await createTailwindAdapter().compile(wideGamut, {});
    expect(result.artifacts[0]?.content).toContain(
      "oklch(0.72 0.28 12 / 0.75)",
    );
  });

  it("rejects selector injection and normalizes hostile variable names", async () => {
    const hostile: ThemeGraph = {
      ...graph(),
      primitives: [
        { id: "A B", $type: "color", value: brand },
        { id: "a-b", $type: "color", value: white },
        {
          id: 'x; } body { background: url("javascript:x")',
          $type: "color",
          value: navy,
        },
      ],
    };
    const result = await createTailwindAdapter({
      prefix: "x;}\nbody",
      darkSelector: "} body { color: red } /*",
    }).compile(hostile, {});
    const content = result.artifacts[0]?.content ?? "";

    expect(content).not.toContain("javascript:");
    expect(content).not.toContain("color: red");
    expect(content).toContain('[data-theme="dark"]');
    expect(content.match(/--color-palette-a-b-[0-9a-f]{8}:/g)).toHaveLength(2);
    expect(result.diagnostics?.map((diagnostic) => diagnostic.code)).toEqual(
      expect.arrayContaining([
        "tailwind.prefix.normalized",
        "tailwind.dark-selector.rejected",
      ]),
    );
  });

  it("rejects a dark selector that aliases another generated scheme", async () => {
    const source = graph();
    const result = await createTailwindAdapter({
      darkSelector: '[data-theme="contrast"]',
    }).compile(
      {
        ...source,
        schemes: [
          ...source.schemes,
          { id: "contrast", roles: source.schemes[0]!.roles },
        ],
      },
      {},
    );
    const content = result.artifacts[0]?.content ?? "";

    expect(result.diagnostics?.map((diagnostic) => diagnostic.code)).toContain(
      "tailwind.dark-selector.conflict",
    );
    expect(content.match(/\[data-theme="contrast"\] \{/g)).toHaveLength(1);
    expect(content).toContain('[data-theme="dark"] {');
    expect(result.preview).toMatchObject({
      runtime: {
        overrides: {
          dark: { selector: '[data-theme="dark"]' },
          contrast: { selector: '[data-theme="contrast"]' },
        },
      },
    });
  });

  it("allocates unique names when normalized values and FNV hashes collide", async () => {
    const result = await createTailwindAdapter().compile(
      {
        ...graph(),
        primitives: [
          {
            id: "collision:)*#!name",
            $type: "color",
            value: brand,
          },
          {
            id: "collision^*^$!name",
            $type: "color",
            value: white,
          },
        ],
        schemes: [],
      },
      {},
    );
    const content = result.artifacts[0]?.content ?? "";

    expect(content).toContain("--color-palette-collision-name-53cbed73:");
    expect(content).toContain("--color-palette-collision-name-53cbed73-2:");
  });

  it("diagnoses missing schemes and asymmetric semantic roles", async () => {
    const noSchemes = await createTailwindAdapter().compile(
      { ...graph(), schemes: [] },
      {},
    );
    expect(
      noSchemes.diagnostics?.map((diagnostic) => diagnostic.code),
    ).toContain("tailwind.no-schemes");

    const source = graph();
    const dark = source.schemes.find((scheme) => scheme.id === "dark");
    if (dark === undefined) throw new Error("Missing dark fixture");
    const asymmetric: ThemeGraph = {
      ...source,
      schemes: [
        source.schemes.find((scheme) => scheme.id === "light")!,
        { ...dark, roles: { primary: dark.roles.primary! } },
      ],
    };
    const result = await createTailwindAdapter().compile(asymmetric, {});
    expect(result.diagnostics?.map((diagnostic) => diagnostic.code)).toContain(
      "tailwind.scheme-role.gap",
    );
  });

  it("runs through compileTheme with valid diagnostics and preview JSON", async () => {
    const result = await compileTheme(project(), [createTailwindAdapter()]);

    expect(result.ok).toBe(true);
    if (!result.ok)
      throw new Error("Expected Tailwind compilation to succeed.");
    expect(result.previews["tailwind@4"]).toMatchObject({
      kind: "tailwind-theme",
      version: "4",
    });
    expect(result.artifacts).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          path: "theme.tailwind.css",
          adapterId: "tailwind@4",
        }),
      ]),
    );
    const css =
      result.artifacts.find(
        (artifact) => artifact.path === "theme.tailwind.css",
      )?.content ?? "";
    expect(css).toContain("--color-palette-brand:");
    expect(css).not.toContain("--color-palette-palette-brand:");
    expect(
      result.diagnostics.map((diagnostic) => diagnostic.code),
    ).not.toContain("adapter.diagnostic.invalid");
  });

  it("coexists with the CSS adapter in one compile", async () => {
    const { createCssAdapter } = await import("@s9rg/theme-adapter-css");
    const result = await compileTheme(project(), [
      createCssAdapter(),
      createTailwindAdapter(),
    ]);

    expect(result.ok).toBe(true);
    if (!result.ok)
      throw new Error("Expected combined compilation to succeed.");
    expect(result.artifacts.map((artifact) => artifact.path)).toEqual([
      "theme.css",
      "theme.tailwind.css",
      "theme.lock.json",
    ]);
    expect(
      result.diagnostics.map((diagnostic) => diagnostic.code),
    ).not.toContain("artifact.path.duplicate");
  });
});

function project(source: ThemeGraph = graph()): ThemeProject {
  return {
    schemaVersion: source.schemaVersion,
    id: source.projectId,
    ...(source.projectName === undefined ? {} : { name: source.projectName }),
    primitives: source.primitives.map((primitive) => ({
      ...primitive,
      id: namespacedPrimitiveId(primitive.id),
    })),
    schemes: source.schemes.map((scheme) => ({
      id: scheme.id,
      roles: Object.fromEntries(
        Object.values(scheme.roles).map((resolvedRole) => [
          resolvedRole.role,
          { ref: namespacedPrimitiveId(resolvedRole.ref) },
        ]),
      ),
    })),
  };
}

function namespacedPrimitiveId(value: string): string {
  return value.startsWith("palette.") ? value : `palette.${value}`;
}
