import { describe, expect, it } from "vitest";
import { compileTheme } from "@s9rg/theme-compiler";
import type {
  ResolvedColor,
  ThemeGraph,
  ThemeProject,
} from "@s9rg/theme-compiler";
import {
  createCssAdapter,
  cssAdapterManifest,
  safeParseCssAdapterPreview,
} from "./index.js";

const brand: ResolvedColor = {
  colorSpace: "srgb",
  components: [0, 0.4, 0.8],
  alpha: 1,
  hex: "#0066cc",
};
const white: ResolvedColor = {
  colorSpace: "srgb",
  components: [1, 1, 1],
  alpha: 1,
  hex: "#ffffff",
};
const navy: ResolvedColor = {
  colorSpace: "srgb",
  components: [0.02, 0.04, 0.08],
  alpha: 1,
  hex: "#050a14",
};

function graph(): ThemeGraph {
  return {
    schemaVersion: "1.0",
    projectId: "acme",
    projectName: "Acme",
    primitives: [
      { id: "white", $type: "color", value: white },
      { id: "brand", $type: "color", value: brand },
      { id: "navy", $type: "color", value: navy },
    ],
    schemes: [
      {
        id: "light",
        roles: {
          "primary-foreground": {
            role: "primary-foreground",
            ref: "white",
            value: white,
          },
          primary: { role: "primary", ref: "brand", value: brand },
          background: { role: "background", ref: "white", value: white },
        },
      },
      {
        id: "dark",
        roles: {
          background: { role: "background", ref: "navy", value: navy },
          primary: { role: "primary", ref: "brand", value: brand },
          "primary-foreground": {
            role: "primary-foreground",
            ref: "white",
            value: white,
          },
        },
      },
    ],
  };
}

describe("CSS adapter", () => {
  it("exposes its versioned capability manifest", () => {
    expect(cssAdapterManifest).toMatchObject({
      id: "css@1",
      engineApiVersion: "1",
      maturity: "beta",
      capabilities: {
        colors: { native: "passthrough", fallback: "none" },
        schemes: { count: "multiple", ids: "any" },
        preview: true,
      },
      options: { prefix: { type: "string", default: "theme" } },
    });
  });

  it("emits deterministic primitive and light/dark semantic variables", async () => {
    const adapter = createCssAdapter();
    const first = await adapter.compile(graph(), {});
    const source = graph();
    const reordered: ThemeGraph = {
      ...source,
      primitives: [...source.primitives].reverse(),
      schemes: [...source.schemes].reverse().map((scheme) => ({
        ...scheme,
        roles: Object.fromEntries(Object.entries(scheme.roles).reverse()),
      })),
    };
    const second = await adapter.compile(reordered, {});
    const content = first.artifacts[0]?.content;

    expect(first.artifacts).toEqual(second.artifacts);
    expect(content).toBe(`/* Generated by @s9rg/theme-adapter-css. */

:root {
  --theme-palette-brand: color(srgb 0 0.4 0.8);
  --theme-palette-navy: color(srgb 0.02 0.04 0.08);
  --theme-palette-white: color(srgb 1 1 1);
  --theme-semantic-background: color(srgb 1 1 1);
  --theme-semantic-primary: color(srgb 0 0.4 0.8);
  --theme-semantic-primary-foreground: color(srgb 1 1 1);
}

[data-theme="dark"] {
  --theme-semantic-background: color(srgb 0.02 0.04 0.08);
  --theme-semantic-primary: color(srgb 0 0.4 0.8);
  --theme-semantic-primary-foreground: color(srgb 1 1 1);
}
`);
    expect(first.preview).toMatchObject({
      kind: "css-custom-properties",
      schemes: {
        light: {
          "--theme-semantic-primary": "color(srgb 0 0.4 0.8)",
        },
      },
      runtime: {
        root: { selector: ":root", scheme: "light" },
        overrides: {
          dark: { selector: '[data-theme="dark"]' },
        },
      },
    });
  });

  it("keeps primitive and semantic namespaces distinct in source and preview", async () => {
    const source = graph();
    const collidingRole: ThemeGraph = {
      ...source,
      schemes: source.schemes.map((scheme) => ({
        ...scheme,
        roles: {
          ...scheme.roles,
          "palette-brand": {
            role: "palette-brand",
            ref: "white",
            value: white,
          },
        },
      })),
    };
    const result = await createCssAdapter().compile(collidingRole, {});
    const content = result.artifacts[0]?.content ?? "";

    expect(content).toContain("--theme-palette-brand: color(srgb 0 0.4 0.8);");
    expect(content).toContain(
      "--theme-semantic-palette-brand: color(srgb 1 1 1);",
    );
    expect(result.preview).toMatchObject({
      schemes: {
        light: {
          "--theme-palette-brand": "color(srgb 0 0.4 0.8)",
          "--theme-semantic-palette-brand": "color(srgb 1 1 1)",
        },
      },
    });
  });

  it("reports root inheritance accurately in an effective scheme preview", async () => {
    const source = graph();
    const dark = source.schemes.find((scheme) => scheme.id === "dark")!;
    const result = await createCssAdapter().compile(
      {
        ...source,
        schemes: [
          source.schemes.find((scheme) => scheme.id === "light")!,
          { ...dark, roles: { background: dark.roles.background! } },
        ],
      },
      {},
    );

    expect(result.preview).toMatchObject({
      schemes: {
        dark: {
          "--theme-semantic-background": "color(srgb 0.02 0.04 0.08)",
          "--theme-semantic-primary": "color(srgb 0 0.4 0.8)",
        },
      },
      runtime: {
        overrides: {
          dark: {
            variables: {
              "--theme-semantic-background": "color(srgb 0.02 0.04 0.08)",
            },
          },
        },
      },
    });
  });

  it("rejects selector injection and disambiguates hostile identifiers", async () => {
    const hostile: ThemeGraph = {
      ...graph(),
      primitives: [
        { id: "A B", $type: "color", value: brand },
        { id: "a-b", $type: "color", value: white },
        {
          id: 'x; } body { background: url("javascript:x")',
          $type: "color",
          value: navy,
        },
      ],
    };
    const result = await createCssAdapter({
      prefix: "x;}\nbody",
      darkSelector: "} body { color: red } /*",
    }).compile(hostile, {});
    const content = result.artifacts[0]?.content ?? "";

    expect(content).not.toContain("javascript:");
    expect(content).not.toContain("color: red");
    expect(content).toContain('[data-theme="dark"]');
    expect(content.match(/--x-body-palette-a-b-[0-9a-f]{8}:/g)).toHaveLength(2);
    expect(result.diagnostics?.map((diagnostic) => diagnostic.code)).toEqual(
      expect.arrayContaining([
        "css.prefix.normalized",
        "css.dark-selector.rejected",
      ]),
    );
  });

  it("reports when semantic schemes are missing", async () => {
    const result = await createCssAdapter().compile(
      { ...graph(), schemes: [] },
      {},
    );
    expect(result.diagnostics?.map((diagnostic) => diagnostic.code)).toContain(
      "css.no-schemes",
    );
    expect(result.artifacts[0]?.content).toContain("--theme-palette-brand");
  });

  it("rejects a dark selector that aliases another generated scheme", async () => {
    const source = graph();
    const result = await createCssAdapter({
      darkSelector: '[data-theme="contrast"]',
    }).compile(
      {
        ...source,
        schemes: [
          ...source.schemes,
          { id: "contrast", roles: source.schemes[0]!.roles },
        ],
      },
      {},
    );
    const content = result.artifacts[0]?.content ?? "";

    expect(result.diagnostics?.map((diagnostic) => diagnostic.code)).toContain(
      "css.dark-selector.conflict",
    );
    expect(content.match(/\[data-theme="contrast"\] \{/g)).toHaveLength(1);
    expect(content).toContain('[data-theme="dark"] {');
    expect(result.preview).toMatchObject({
      runtime: {
        overrides: {
          dark: { selector: '[data-theme="dark"]' },
          contrast: { selector: '[data-theme="contrast"]' },
        },
      },
    });
  });

  it("allocates unique names when normalized values and FNV hashes collide", async () => {
    const firstId = "collision:)*#!name";
    const secondId = "collision^*^$!name";
    const result = await createCssAdapter().compile(
      {
        ...graph(),
        primitives: [
          { id: firstId, $type: "color", value: brand },
          { id: secondId, $type: "color", value: white },
        ],
        schemes: [],
      },
      {},
    );
    const content = result.artifacts[0]?.content ?? "";

    expect(content).toContain("--theme-palette-collision-name-53cbed73:");
    expect(content).toContain("--theme-palette-collision-name-53cbed73-2:");
  });

  it("honors an already-aborted compilation context", () => {
    const controller = new AbortController();
    controller.abort(new Error("stop"));
    expect(() =>
      createCssAdapter().compile(graph(), { signal: controller.signal }),
    ).toThrow("stop");
  });

  it("runs through compileTheme with a valid preview and artifact", async () => {
    const result = await compileTheme(project(), [createCssAdapter()]);

    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error("Expected CSS compilation to succeed.");
    expect(result.previews["css@1"]).toMatchObject({
      kind: "css-custom-properties",
      version: "1",
    });
    expect(result.artifacts).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ path: "theme.css", adapterId: "css@1" }),
      ]),
    );
    const css =
      result.artifacts.find((artifact) => artifact.path === "theme.css")
        ?.content ?? "";
    expect(css).toContain("--theme-palette-brand:");
    expect(css).not.toContain("--theme-palette-palette-brand:");
    expect(
      result.diagnostics.map((diagnostic) => diagnostic.code),
    ).not.toContain("adapter.diagnostic.invalid");
  });

  it("snapshots normalized options and records them in the lockfile", async () => {
    const options = { prefix: "Product Brand", darkSelector: ".night" };
    const adapter = createCssAdapter(options);
    options.prefix = "changed";
    options.darkSelector = ".changed";

    expect(adapter.configuration).toEqual({
      prefix: "product-brand",
      darkSelector: ".night",
    });
    const result = await compileTheme(project(), [adapter]);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error("Expected CSS compilation to succeed.");
    expect(result.artifacts[0]?.content).toContain(
      "--product-brand-palette-brand:",
    );
    expect(result.artifacts[0]?.content).toContain(".night {");
    const lock = JSON.parse(result.lockfile.content) as {
      adapters: { configuration?: unknown }[];
    };
    expect(lock.adapters[0]?.configuration).toEqual({
      darkSelector: ".night",
      prefix: "product-brand",
    });
  });

  it("parses emitted previews and contains hostile unknown inputs", async () => {
    const output = await createCssAdapter().compile(graph(), {});
    const parsed = safeParseCssAdapterPreview(output.preview);
    expect(parsed.success).toBe(true);

    let reads = 0;
    const accessor: Record<string, unknown> = {};
    Object.defineProperty(accessor, "kind", {
      enumerable: true,
      get: () => {
        reads += 1;
        return "css-custom-properties";
      },
    });
    const { proxy, revoke } = Proxy.revocable({}, {});
    revoke();

    expect(safeParseCssAdapterPreview(accessor).success).toBe(false);
    expect(reads).toBe(0);
    expect(() => safeParseCssAdapterPreview(proxy)).not.toThrow();
    expect(safeParseCssAdapterPreview(proxy).success).toBe(false);
  });
});

function project(source: ThemeGraph = graph()): ThemeProject {
  return {
    schemaVersion: source.schemaVersion,
    id: source.projectId,
    ...(source.projectName === undefined ? {} : { name: source.projectName }),
    primitives: source.primitives.map((primitive) => ({
      ...primitive,
      id: namespacedPrimitiveId(primitive.id),
    })),
    schemes: source.schemes.map((scheme) => ({
      id: scheme.id,
      roles: Object.fromEntries(
        Object.values(scheme.roles).map((resolvedRole) => [
          resolvedRole.role,
          { ref: namespacedPrimitiveId(resolvedRole.ref) },
        ]),
      ),
    })),
  };
}

function namespacedPrimitiveId(value: string): string {
  return value.startsWith("palette.") ? value : `palette.${value}`;
}
